/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/features/**/*.{js,jsx,ts,tsx}",
    "./src/layouts/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#154539',
          container: '#2f5d50',
          fixed: '#bceddc',
          'fixed-dim': '#a0d1c0',
        },
        secondary: {
          DEFAULT: '#5e5e5e',
          container: '#e1dfdf',
          fixed: '#e4e2e2',
          'fixed-dim': '#c7c6c6',
        },
        tertiary: {
          DEFAULT: '#5d322a',
          container: '#784840',
        },
        background: {
          DEFAULT: '#f9faf7',
        },
        surface: {
          DEFAULT: '#f9faf7',
          dim: '#d9dad8',
          bright: '#f9faf7',
          'container-lowest': '#ffffff',
          'container-low': '#f3f4f1',
          container: '#edeeec',
          'container-high': '#e7e8e6',
          'container-highest': '#e2e3e0',
          variant: '#e2e3e0',
        },
        text: {
          DEFAULT: '#1a1c1b',
          muted: '#404945',
          inverse: '#ffffff',
        },
        border: {
          DEFAULT: '#c0c8c4', // outline-variant
          strong: '#717975',  // outline
        },
        status: {
          success: '#16a34a', // Keeping semantic defaults if unprovided
          warning: '#ca8a04',
          error: '#ba1a1a',   // From design spec
        },
        alumni: {
          primary: '#3525cd',
          'primary-container': '#4f46e5',
          'on-primary-container': '#dad7ff',
          'on-primary': '#ffffff',
          'primary-fixed': '#e2dfff',
          'primary-fixed-dim': '#c3c0ff',
          'on-primary-fixed-variant': '#3323cc',
          secondary: '#5b598c',
          'secondary-fixed': '#e3dfff',
          'on-secondary-fixed': '#181445',
          tertiary: '#3a495f',
          'tertiary-fixed': '#d3e4fe',
          'on-tertiary-fixed': '#0b1c30',
          surface: '#f8f9ff',
          'surface-card': '#ffffff',
          'surface-container-low': '#f2f3f9',
          'surface-container-high': '#e7e8ee',
          'surface-container-highest': '#e1e2e8',
          'surface-dim': '#d8dae0',
          'on-surface': '#191c20',
          'on-surface-variant': '#464555',
          'border-subtle': '#e2e8f0',
          outline: '#777587',
        },
        student: {
          primary: '#3525cd',
          'primary-container': '#4f46e5',
          'on-primary-container': '#dad7ff',
          'on-primary': '#ffffff',
          'primary-fixed': '#e2dfff',
          'primary-fixed-dim': '#c3c0ff',
          'on-primary-fixed-variant': '#3323cc',
          secondary: '#5c5f61',
          'secondary-fixed': '#e0e3e5',
          'on-secondary-fixed': '#191c1e',
          tertiary: '#3e495d',
          'tertiary-fixed': '#d8e3fb',
          'on-tertiary-fixed': '#111c2d',
          surface: '#f8f9ff',
          'surface-card': '#ffffff',
          'surface-container-low': '#eff4ff',
          'surface-container-high': '#dce9ff',
          'surface-container-highest': '#d3e4fe',
          'surface-dim': '#cbdbf5',
          'on-surface': '#0b1c30',
          'on-surface-variant': '#464555',
          'border-subtle': '#e2e8f0',
          outline: '#777587',
        },
        institute: {
          primary: '#3525cd',
          'primary-container': '#4f46e5',
          'on-primary-container': '#dad7ff',
          'on-primary': '#ffffff',
          'primary-fixed': '#e2dfff',
          'primary-fixed-dim': '#c3c0ff',
          'on-primary-fixed-variant': '#3323cc',
          secondary: '#5c5f61',
          'secondary-fixed': '#e0e3e5',
          'on-secondary-fixed': '#191c1e',
          tertiary: '#3e495d',
          'tertiary-fixed': '#d8e3fb',
          'on-tertiary-fixed': '#111c2d',
          surface: '#f8f9ff',
          'surface-card': '#ffffff',
          'surface-container-low': '#eff4ff',
          'surface-container-high': '#dce9ff',
          'surface-container-highest': '#d3e4fe',
          'surface-dim': '#cbdbf5',
          'on-surface': '#0b1c30',
          'on-surface-variant': '#464555',
          'border-subtle': '#e2e8f0',
          outline: '#777587',
        },
        admin: {
          primary: '#3525cd',
          'primary-container': '#4f46e5',
          'on-primary-container': '#dad7ff',
          'on-primary': '#ffffff',
          'primary-fixed': '#e2dfff',
          'primary-fixed-dim': '#c3c0ff',
          'on-primary-fixed-variant': '#3323cc',
          secondary: '#5b598c',
          'secondary-fixed': '#e3dfff',
          'on-secondary-fixed': '#181445',
          tertiary: '#3a495f',
          'tertiary-fixed': '#d3e4fe',
          'on-tertiary-fixed': '#0b1c30',
          surface: '#f8f9ff',
          'surface-card': '#ffffff',
          'surface-container-low': '#f2f3f9',
          'surface-container-high': '#e7e8ee',
          'surface-container-highest': '#e1e2e8',
          'surface-dim': '#d8dae0',
          'on-surface': '#191c20',
          'on-surface-variant': '#464555',
          'border-subtle': '#e2e8f0',
          outline: '#777587',
        }
      },
      fontFamily: {
        sans: ['Inter', 'System', 'sans-serif'],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        '2xl': '64px',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        DEFAULT: '0 4px 20px rgba(0,0,0,0.04)', // Ambient Shadow defined in DESIGN.md
      }
    },
  },
  plugins: [],
}
