import os

def create_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

backend_dir = r"c:\Users\tejas\OneDrive\Desktop\ALumini\backend"

reqs = """sqlalchemy[asyncio]==2.0.23\nalembic==1.13.1\nasyncpg==0.29.0"""
create_file(os.path.join(backend_dir, "requirements.txt"), reqs)

alembic_ini = """[alembic]\nscript_location = alembic\nprepend_sys_path = .\nversion_path_separator = os\nsqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/almabridge\n\n[post_write_hooks]\n[loggers]\nkeys = root,sqlalchemy,alembic\n[handlers]\nkeys = console\n[formatters]\nkeys = generic\n[logger_root]\nlevel = WARN\nhandlers = console\nqualname =\n[logger_sqlalchemy]\nlevel = WARN\nhandlers =\nqualname = sqlalchemy.engine\n[logger_alembic]\nlevel = INFO\nhandlers =\nqualname = alembic\n[handler_console]\nclass = StreamHandler\nargs = (sys.stderr,)\nlevel = NOTSET\nformatter = generic\n[formatter_generic]\nformat = %(levelname)-5.5s [%(name)s] %(message)s\ndatefmt = %H:%M:%S"""
create_file(os.path.join(backend_dir, "alembic.ini"), alembic_ini)

base_py = """import uuid\nfrom datetime import datetime\nfrom sqlalchemy.orm import declarative_base, Mapped, mapped_column\nfrom sqlalchemy import DateTime, text\nfrom sqlalchemy.dialects.postgresql import UUID\n\nBase = declarative_base()\n\nclass BaseModel(Base):\n    __abstract__ = True\n\n    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)\n    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))\n    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"), onupdate=text("now()"))"""
create_file(os.path.join(backend_dir, "models", "base.py"), base_py)

enums_py = """import enum\n\nclass UserRole(str, enum.Enum):\n    STUDENT = "STUDENT"\n    ALUMNI = "ALUMNI"\n    PLACEMENT_CELL = "PLACEMENT_CELL"\n    ADMIN = "ADMIN"\n\nclass OpportunityStatus(str, enum.Enum):\n    OPEN = "OPEN"\n    CLOSED = "CLOSED"\n\nclass CommunityVisibility(str, enum.Enum):\n    PUBLIC = "PUBLIC"\n    PRIVATE = "PRIVATE"\n\nclass MentorshipStatus(str, enum.Enum):\n    PENDING = "PENDING"\n    ACCEPTED = "ACCEPTED"\n    REJECTED = "REJECTED"\n\nclass NotificationType(str, enum.Enum):\n    INFO = "INFO"\n    ALERT = "ALERT"\n    MESSAGE = "MESSAGE\""""
create_file(os.path.join(backend_dir, "models", "enums.py"), enums_py)

lookups_py = """from sqlalchemy import String\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom .base import BaseModel\n\nclass Department(BaseModel):\n    __tablename__ = "department"\n    name: Mapped[str] = mapped_column(String, unique=True, index=True)\n\nclass Industry(BaseModel):\n    __tablename__ = "industry"\n    name: Mapped[str] = mapped_column(String, unique=True, index=True)\n\nclass Skill(BaseModel):\n    __tablename__ = "skill"\n    name: Mapped[str] = mapped_column(String, unique=True, index=True)\n\nclass CommunityCategory(BaseModel):\n    __tablename__ = "community_category"\n    name: Mapped[str] = mapped_column(String, unique=True, index=True)\n\nclass OpportunityType(BaseModel):\n    __tablename__ = "opportunity_type"\n    name: Mapped[str] = mapped_column(String, unique=True, index=True)"""
create_file(os.path.join(backend_dir, "models", "lookups.py"), lookups_py)

user_py = """from sqlalchemy import String, Boolean, Enum\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom .base import BaseModel\nfrom .enums import UserRole\n\nclass User(BaseModel):\n    __tablename__ = "user"\n\n    email: Mapped[str] = mapped_column(String, unique=True, index=True)\n    external_auth_id: Mapped[str] = mapped_column(String, unique=True, nullable=True)\n    role: Mapped[UserRole] = mapped_column(Enum(UserRole, name="userrole_enum"))\n    is_active: Mapped[bool] = mapped_column(Boolean, default=True)\n    first_name: Mapped[str] = mapped_column(String, nullable=True)\n    last_name: Mapped[str] = mapped_column(String, nullable=True)\n    avatar_url: Mapped[str] = mapped_column(String, nullable=True)"""
create_file(os.path.join(backend_dir, "models", "user.py"), user_py)

profiles_py = """import uuid\nfrom sqlalchemy import String, Integer, Boolean, ForeignKey\nfrom sqlalchemy.orm import Mapped, mapped_column, relationship\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\n\nclass StudentProfile(BaseModel):\n    __tablename__ = "student_profile"\n\n    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="CASCADE"), unique=True)\n    department_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("department.id", ondelete="SET NULL"), nullable=True)\n    graduation_year: Mapped[int] = mapped_column(Integer, nullable=True)\n    resume_url: Mapped[str] = mapped_column(String, nullable=True)\n    bio: Mapped[str] = mapped_column(String, nullable=True)\n\nclass AlumniProfile(BaseModel):\n    __tablename__ = "alumni_profile"\n\n    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="CASCADE"), unique=True)\n    company: Mapped[str] = mapped_column(String, nullable=True)\n    position: Mapped[str] = mapped_column(String, nullable=True)\n    industry_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("industry.id", ondelete="SET NULL"), nullable=True)\n    experience_years: Mapped[int] = mapped_column(Integer, nullable=True)\n    bio: Mapped[str] = mapped_column(String, nullable=True)\n    mentorship_available: Mapped[bool] = mapped_column(Boolean, default=False)"""
create_file(os.path.join(backend_dir, "models", "profiles.py"), profiles_py)

junctions_py = """import uuid\nfrom datetime import datetime\nfrom sqlalchemy import ForeignKey, DateTime, text\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\n\nclass StudentSkill(BaseModel):\n    __tablename__ = "student_skill"\n    student_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("student_profile.id", ondelete="CASCADE"), index=True)\n    skill_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("skill.id", ondelete="CASCADE"), index=True)\n\nclass AlumniSkill(BaseModel):\n    __tablename__ = "alumni_skill"\n    alumni_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("alumni_profile.id", ondelete="CASCADE"), index=True)\n    skill_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("skill.id", ondelete="CASCADE"), index=True)\n\nclass OpportunitySkill(BaseModel):\n    __tablename__ = "opportunity_skill"\n    opportunity_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("opportunity.id", ondelete="CASCADE"), index=True)\n    skill_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("skill.id", ondelete="CASCADE"), index=True)\n\nclass CommunityMembership(BaseModel):\n    __tablename__ = "community_membership"\n    community_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("community.id", ondelete="CASCADE"), index=True)\n    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="CASCADE"), index=True)\n    joined_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))\n\nclass EventRegistration(BaseModel):\n    __tablename__ = "event_registration"\n    event_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("event.id", ondelete="CASCADE"), index=True)\n    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="CASCADE"), index=True)\n    registered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))"""
create_file(os.path.join(backend_dir, "models", "junctions.py"), junctions_py)

opportunity_py = """import uuid\nfrom datetime import datetime\nfrom sqlalchemy import String, Enum, DateTime, ForeignKey\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\nfrom .enums import OpportunityStatus\n\nclass Opportunity(BaseModel):\n    __tablename__ = "opportunity"\n\n    title: Mapped[str] = mapped_column(String, index=True)\n    description: Mapped[str] = mapped_column(String)\n    opportunity_type_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("opportunity_type.id", ondelete="SET NULL"), nullable=True)\n    company: Mapped[str] = mapped_column(String)\n    location: Mapped[str] = mapped_column(String, nullable=True)\n    deadline: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)\n    status: Mapped[OpportunityStatus] = mapped_column(Enum(OpportunityStatus, name="opportunitystatus_enum"))\n    created_by: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="SET NULL"), nullable=True)\n    deleted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True, index=True)"""
create_file(os.path.join(backend_dir, "models", "opportunity.py"), opportunity_py)

community_py = """import uuid\nfrom datetime import datetime\nfrom sqlalchemy import String, Enum, DateTime, ForeignKey\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID, ARRAY\nfrom .base import BaseModel\nfrom .enums import CommunityVisibility\n\nclass Community(BaseModel):\n    __tablename__ = "community"\n\n    name: Mapped[str] = mapped_column(String, unique=True, index=True)\n    description: Mapped[str] = mapped_column(String, nullable=True)\n    category_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("community_category.id", ondelete="SET NULL"), nullable=True)\n    cover_image_url: Mapped[str] = mapped_column(String, nullable=True)\n    visibility: Mapped[CommunityVisibility] = mapped_column(Enum(CommunityVisibility, name="communityvisibility_enum"))\n    created_by: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="SET NULL"), nullable=True)\n    deleted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True, index=True)\n\nclass CommunityPost(BaseModel):\n    __tablename__ = "community_post"\n\n    community_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("community.id", ondelete="CASCADE"), index=True)\n    author_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="SET NULL"), nullable=True)\n    content: Mapped[str] = mapped_column(String)\n    images: Mapped[list[str]] = mapped_column(ARRAY(String), nullable=True)\n    deleted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)"""
create_file(os.path.join(backend_dir, "models", "community.py"), community_py)

event_py = """import uuid\nfrom datetime import datetime\nfrom sqlalchemy import String, Integer, DateTime, ForeignKey\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\n\nclass Event(BaseModel):\n    __tablename__ = "event"\n\n    title: Mapped[str] = mapped_column(String)\n    description: Mapped[str] = mapped_column(String, nullable=True)\n    banner_url: Mapped[str] = mapped_column(String, nullable=True)\n    venue: Mapped[str] = mapped_column(String, nullable=True)\n    event_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)\n    organizer_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="SET NULL"), nullable=True)\n    capacity: Mapped[int] = mapped_column(Integer, nullable=True)\n    registration_deadline: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)"""
create_file(os.path.join(backend_dir, "models", "event.py"), event_py)

mentorship_py = """import uuid\nfrom datetime import datetime\nfrom sqlalchemy import String, Enum, DateTime, ForeignKey, text\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\nfrom .enums import MentorshipStatus\n\nclass MentorshipRequest(BaseModel):\n    __tablename__ = "mentorship_request"\n\n    mentor_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("alumni_profile.id", ondelete="CASCADE"), index=True)\n    student_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("student_profile.id", ondelete="CASCADE"), index=True)\n    status: Mapped[MentorshipStatus] = mapped_column(Enum(MentorshipStatus, name="mentorshipstatus_enum"))\n    notes: Mapped[str] = mapped_column(String, nullable=True)\n    request_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"))\n    accepted_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)"""
create_file(os.path.join(backend_dir, "models", "mentorship.py"), mentorship_py)

file_py = """import uuid\nfrom sqlalchemy import String, Integer, ForeignKey\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\n\nclass FileMetadata(BaseModel):\n    __tablename__ = "file_metadata"\n\n    uploader_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="SET NULL"), nullable=True)\n    bucket_name: Mapped[str] = mapped_column(String)\n    file_path: Mapped[str] = mapped_column(String)\n    file_type: Mapped[str] = mapped_column(String, nullable=True)\n    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=True)"""
create_file(os.path.join(backend_dir, "models", "file.py"), file_py)

notification_py = """import uuid\nfrom sqlalchemy import String, Boolean, Enum, ForeignKey\nfrom sqlalchemy.orm import Mapped, mapped_column\nfrom sqlalchemy.dialects.postgresql import UUID\nfrom .base import BaseModel\nfrom .enums import NotificationType\n\nclass Notification(BaseModel):\n    __tablename__ = "notification"\n\n    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.id", ondelete="CASCADE"), index=True)\n    type: Mapped[NotificationType] = mapped_column(Enum(NotificationType, name="notificationtype_enum"))\n    title: Mapped[str] = mapped_column(String)\n    message: Mapped[str] = mapped_column(String)\n    is_read: Mapped[bool] = mapped_column(Boolean, default=False)"""
create_file(os.path.join(backend_dir, "models", "notification.py"), notification_py)

init_py = """from .base import Base, BaseModel\nfrom .enums import UserRole, OpportunityStatus, CommunityVisibility, MentorshipStatus, NotificationType\nfrom .lookups import Department, Industry, Skill, CommunityCategory, OpportunityType\nfrom .user import User\nfrom .profiles import StudentProfile, AlumniProfile\nfrom .junctions import StudentSkill, AlumniSkill, OpportunitySkill, CommunityMembership, EventRegistration\nfrom .community import Community, CommunityPost\nfrom .opportunity import Opportunity\nfrom .event import Event\nfrom .mentorship import MentorshipRequest\nfrom .file import FileMetadata\nfrom .notification import Notification\n\n__all__ = [\n    "Base", "BaseModel", "UserRole", "OpportunityStatus", "CommunityVisibility", "MentorshipStatus", "NotificationType",\n    "Department", "Industry", "Skill", "CommunityCategory", "OpportunityType",\n    "User", "StudentProfile", "AlumniProfile",\n    "StudentSkill", "AlumniSkill", "OpportunitySkill", "CommunityMembership", "EventRegistration",\n    "Community", "CommunityPost", "Opportunity", "Event", "MentorshipRequest", "FileMetadata", "Notification"\n]"""
create_file(os.path.join(backend_dir, "models", "__init__.py"), init_py)

print("Backend files generated.")
