"""legacy_cleanup_and_foundation

Revision ID: 17fe282f8663
Revises: 1e002ebe1d6c
Create Date: 2026-08-19 01:12:48.772704

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fe282f8663'
down_revision: Union[str, None] = '1e002ebe1d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='announcementstatus_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('alumni_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_info', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='referralstatus_enum'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('reported_entity_type', sa.String(), nullable=False),
    sa.Column('reported_entity_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='reportstatus_enum'), nullable=False),
    sa.Column('moderation_action', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_placement_drive_company_id', table_name='placement_drive')
    op.drop_table('placement_drive')
    op.drop_index('ix_company_relationship_company_id', table_name='company_relationship')
    op.drop_table('company_relationship')
    op.drop_table('placement_cell')
    
    op.drop_constraint('user_company_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_institution_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'institution_id')
    op.drop_column('user', 'company_id')

    op.drop_index('ix_company_name', table_name='company')
    op.drop_table('company')
    op.create_unique_constraint('uq_event_registration_user_event', 'event_registration', ['user_id', 'event_id'])
    op.create_unique_constraint('uq_job_application_user_opp', 'job_application', ['user_id', 'opportunity_id'])
    op.create_index('uq_active_mentorship', 'mentorship_request', ['mentor_id', 'student_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'ACCEPTED')"))
    # Safe Enum migration strategy for PostgreSQL
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        userrole_enum = sa.Enum('STUDENT', 'ALUMNI', 'INSTITUTE', 'ADMIN', name='userrole_enum')
        userrole_enum.create(bind, checkfirst=True)
        op.execute("ALTER TABLE \"user\" ALTER COLUMN role TYPE userrole_enum USING role::text::userrole_enum")
    else:
        op.alter_column('user', 'role',
                   existing_type=sa.VARCHAR(length=17),
                   type_=sa.Enum('STUDENT', 'ALUMNI', 'INSTITUTE', 'ADMIN', name='userrole_enum'),
                   existing_nullable=False)
    # Foreign keys and columns were dropped above
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company_id', sa.CHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('institution_id', sa.CHAR(length=32), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        # Convert back to varchar
        op.execute("ALTER TABLE \"user\" ALTER COLUMN role TYPE VARCHAR(17) USING role::text")
        # Do not blindly drop userrole_enum here if other tables might use it, but safe to drop if exclusive
        op.execute("DROP TYPE IF EXISTS userrole_enum")
    else:
        op.alter_column('user', 'role',
                   existing_type=sa.Enum('STUDENT', 'ALUMNI', 'INSTITUTE', 'ADMIN', name='userrole_enum'),
                   type_=sa.VARCHAR(length=17),
                   existing_nullable=False)
    op.drop_index('uq_active_mentorship', table_name='mentorship_request', postgresql_where=sa.text("status IN ('PENDING', 'ACCEPTED')"))
    op.drop_constraint('uq_job_application_user_opp', 'job_application', type_='unique')
    op.drop_constraint('uq_event_registration_user_event', 'event_registration', type_='unique')
    op.create_table('placement_drive',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('company_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('eligible_batches', sa.VARCHAR(), nullable=True),
    sa.Column('eligible_departments', sa.VARCHAR(), nullable=True),
    sa.Column('drive_date', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_drive_company_id', 'placement_drive', ['company_id'], unique=False)
    op.create_table('placement_cell',
    sa.Column('institution_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('website', sa.VARCHAR(), nullable=True),
    sa.Column('industry', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_name', 'company', ['name'], unique=1)
    op.create_table('company_relationship',
    sa.Column('company_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('account_manager_id', sa.CHAR(length=32), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(true)'), nullable=False),
    sa.ForeignKeyConstraint(['account_manager_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_relationship_company_id', 'company_relationship', ['company_id'], unique=1)
    op.drop_table('report')
    op.drop_table('referral')
    op.drop_table('announcement')
    # ### end Alembic commands ###