"""Add Connection model

Revision ID: 40be30bffdde
Revises: cf6527e1a235
Create Date: 2026-08-19 02:32:42.747627

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40be30bffdde'
down_revision: Union[str, None] = 'cf6527e1a235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='connectionstatus_enum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('requester_id != target_id', name='check_no_self_connection'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'target_id', name='uq_connection_requester_target')
    )
    op.create_index(op.f('ix_connection_requester_id'), 'connection', ['requester_id'], unique=False)
    op.create_index(op.f('ix_connection_target_id'), 'connection', ['target_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_target_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_requester_id'), table_name='connection')
    op.drop_table('connection')
    # ### end Alembic commands ###